sudo: required
dist: trusty
services:
- docker
install:
- docker build -t test .
script:
- docker run -ti test /bin/true
notifications:
  email: false
  slack:
    secure: Eq75BunBt1pJ5U3Xc4SfgG7POU07ioHlgDpx1GA6lCeU7dMpzxQ4oQ5T8nNIl7gekgC0ImblvHNy0yOvlt/xmfUHfA41AD3tfeg69Qxc9JMvxSxyw8a6meLxf1kfqEqlNj3RXz+SimfxOXo5u6uAIXmoMK07sz+Incj6Zv6ybJzIO8kHLWjuNV03viR+6s88fGGHhV0zHyf2kcC8nycd9RTlWgIKUmngGhijfzv/XKWKoBIlLO71ydr2fzaG0Lh74/Oycr8IBIcYUecQoygn/oFxlf4XhShmpJyTq+q9iLDAEtRnMDIjemDcG3zi9FK4DsIesSazWd9tAM0ZgCrjbByaJLPa4hjl4ewlhrkc2WkXf+ClgUMAzq6tAi72VPf8KRVt4d9hGn9AGEj75JA7w7Q6JXck8u+8BGZrm/52XPbUlWPVtHqWWITl77T00U+KIwrsqIRwVfanB/PWTlwtr40ON0Y9zURUBTP/BuTjmIBzKJsq/oQ9nuW8pO7qgRiuwTKJ8lVlrgHdJaR3CACzAZr+ASK1fV8v8uGFWlPWsBnqwxX0qLfuQLXD3zq3bW1i1BtzkTmBb4Vem/8Wv96ihXYyfi71l5aNZQGb63sNgI/ef4YAnaDLAcS60wrX26deCdVuDmcC3i04GtF3iJJeYH8rCa8Rk1QXI3OI/G/FgMs=
